swagger: '2.0'

securityDefinitions:
  Bearer:
    type: JWT
    name: Authorization
    in: header
  BasicAuth:
    type: basic

components:
  parameters:
    pageParam:
      in: query
      name: page
      required: false
      schema:
        type: integer
        minimum: 0
      description: The number of page of the result set.
    limitParam:
      in: query
      name: limit
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 50
        default: 20
      description: The numbers of items to return per page.

  properties:
    totalProperty:
      type: integer
      format: int64
      example: 76
    pageProperty:
      type: integer
      format: int64
      example: 1
    pagesProperty:
      type: integer
      format: int64
      example: 8
    linksProperty:
      type: object
      properties:
        self:
          type: string
          example: "{endpoint_path}?page=1&per-page=10"
        next:
          type: string
          example: "{endpoint_path}?page=2&per-page=10"
        last:
          type: string
          example: "{endpoint_path}?page=8&per-page=10"

definitions:
  ContainerNotFound:
    description: Not found
    schema:
      type: object
      properties:
        code:
          type: integer
          example: 404
        message:
          type: string
          example: Content container not found!