swagger: '2.0'
info:
  description: |
    Welcome to the HumHub wiki module API reference.

  version: 1.0.0
  title: HumHub - Wiki API
  contact:
    email: info@humhub.com
  license:
    name: AGPLv2
    url: 'https://www.humhub.org/en/licences'
basePath: /api/v1

paths:
  '/space':
    get:
      summary: Find all Spaces
      description: ''
      produces:
        - application/json
        - application/xml
      parameters:
        - in: query
          name: q
          description: name, description, or tag to filter spaces with
          type: string
        - $ref: 'common.yaml#/components/parameters/pageParam'
        - $ref: 'common.yaml#/components/parameters/limitParam'
      responses:
        '200':
          description: Successful operation
          schema:
            type: object
            properties:
              total:
                $ref: 'common.yaml#/components/properties/totalProperty'
              page:
                $ref: 'common.yaml#/components/properties/pageProperty'
              results:
                type: array
                items:
                  $ref: '#/definitions/Space'
    post:
      summary: Create Space
      description: ''
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          description: The space
          required: true
          schema:
            type: object
            $ref: "#/definitions/Space"

      responses:
        '200':
          description: successful operation
          schema:
            $ref: "#/definitions/Space"
        '400':
          description: Invalid post id supplied
        '404':
          description: Wiki page not found

  '/space/{containerId}':
    get:
      summary: Get Space by id
      description: ''
      produces:
        - application/json
      parameters:
        - name: containerId
          in: path
          description: The id of the space
          required: true
          type: integer
      responses:
        '200':
          description: successful operation
          schema:
            $ref: "#/definitions/Space"
        '400':
          description: Invalid post id supplied
        '404':
          description: Wiki page not found
    delete:
      summary: Deletes a space by id
      produces:
        - application/json
      parameters:
        - name: containerId
          in: path
          description: The id of space
          required: true
          type: integer
      responses:
        '200':
          description: successful operation
        '404':
          description: Wiki page not found

    put:
      summary: Update a space
      produces:
        - application/json
      parameters:
        - name: containerId
          in: path
          description: The id of space
          required: true
          type: integer
        - name: body
          in: body
          description: The space
          required: true
          schema:
            type: object
            $ref: "#/definitions/Space"

      responses:
        '200':
          description: successful operation
        '404':
          description: Wiki page not found



securityDefinitions:
  $ref: "common.yaml#/securityDefinitions"

definitions:
  Space:
    type: object
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
        example: 201
      name:
        type: string
        example: "Some space name"
      description:
        type: string
        example: "Some space description"
      tags:
        type: string
        example: "tag1,tag2"
      join_policy:
        type: integer
        format: int64
        enum: [0,1]
      visibility:
        type: integer
        format: int64
        enum: [0,1]
        example: 1
      status:
        type: integer
        format: int64
        example: 1
        enum: [0,1]
      created_by:
        schema:
          type: object
          $ref: "content.yaml#/definitions/Content"


